### ISSUE TITLE
元素水平、垂直居中

### ISSUE THREAD

**Issue by juzhiyuan** [juzhiyuan/blog#9]

**Comment by juzhiyuan** [comment]
### 固定宽高、绝对定位元素
```css
.element {
  width: 100px;
  height: 100px;
  position: absolute;
  left: 50%;
  top: 50%;
  margin-top: -50px;
  margin-left: -50px;
}
```

**Comment by juzhiyuan** [comment]
### 固定宽高、绝对定位元素

```css
.element {
  width: 100px;
  height: 100px;
  position: absolute;
  left: 50%;
  top: 50%;

  // 50% 为自身尺寸一半
  transform: translate(-50%. -50%);
}
```

- transform 偏移的百分比值是相对自身大小的

**Comment by juzhiyuan** [comment]
### margin: auto

```css
.element {
  width: 100px;
  height: 100px;
  position: absolute;

  left: 50%;
  top: 50%;
  right: 0;
  bottom: 0;
  margin: auto;
}
```

#### 注意
- 上下左右均0位置定位
- **margin: auto**
- 可以不设置尺寸（需要是图片这种自身包含尺寸的元素）

**Comment by juzhiyuan** [comment]
### Flex

```html
<div class="container">
  <div class="box">一些元素</div>
</div>
```

```css
.container {
  display: flex;
  justify-content: center;
  aligin-items: center;
}
```

**Comment by juzhiyuan** [comment]
### 行内元素
父级元素设置```text-aligin: center;```即可

**Comment by juzhiyuan** [comment]
### Grid
```css
.container {
  display: grid;
  grid-template-columns: 50px;
  justify-content: center;
}
```
